ALL : chat_server_prototype chat_client

chat_server_prototype : chat_server_prototype.c
	gcc -o chat_server_prototype chat_server_prototype.c

chat_client : chat_client.c
	gcc -o chat_client chat_client.c

